name: Ping
on:
  workflow_dispatch:
    inputs:
      msg:
        description: "Say something"
        required: true
        default: hi
        type: string
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Message: ${{ github.event.inputs.msg }}"
