name: Release
on:
  push:
    branches:
      - feature/**
  workflow_dispatch:
    inputs:
      release_type:
        description: >
          Select the type of release:
          - major: Breaking changes or significant new features.
          - minor: Backward-compatible feature additions.
          - patch: Bug fixes and small changes.
          - snapshot: For libraries/Spring Boot starter; valid on all branches.
        required: true
        default: patch
        type: choice
        options: 
          - major
          - minor
          - patch
          - snapshot
