name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: |
          Select the type of release:
           major: Breaking changes.
           minor: New features.
           patch: Bug fixes.
           snapshot: For libraries, Valid on all branches.
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - snapshot

jobs:
  release:
    if: >
      (inputs.release_type != 'snapshot' && github.ref_name == 'main') ||
      (inputs.release_type == 'snapshot')
