name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: |
          Select the type of release:
           major: Breaking changes.
           minor: New features.
           patch: Bug fixes.
           snapshot: For libraries, Valid on all branches.
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - snapshot
        project_type:
        description: "service | library"
        required: true
        type: choice
        options: [service, library]

jobs:
  release:
    if: |
      (inputs.release_type != 'snapshot' && github.ref_name == 'main') ||
      (inputs.release_type == 'snapshot' && inputs.project_type == 'library') ||
      (inputs.release_type == 'snapshot' && inputs.project_type == 'service' && github.ref_name == 'main')
