name: Ping

on:
  workflow_dispatch:
    inputs:
      msg:
        description: "Message to echo"
        required: true
        default: "hello"
        type: string
      release_type:
        description: "Pick a release type"
        required: true
        default: patch
        type: choice
        options: [major, minor, patch, snapshot]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "msg = ${{ github.event.inputs.msg }}"
          echo "release_type = ${{ github.event.inputs.release_type }}"
